version: '3.7'
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 80:8080
    depends_on:
      db:
        condition: service_healthy
        restart: true

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=animal
      - POSTGRES_USER=maria
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: "pwd"
